server:
  port: 8080

spring:
  application:
    name: Rivendel Challenge

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

  datasource:
    #url: jdbc:h2:mem:rivendeldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:file:/home/valterfi/eclipse-workspace/rivendel-challenge/src/main/resources/h2/rivendeldb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    platform: h2

  h2:
    console:
      enabled: true
      path: /console